name: Go unit tests

on:
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Run unit tests.
        run: make unit_test

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./cover.out
